name-template: "Release v$RESOLVED_VERSION-beta"
tag-template: "v$RESOLVED_VERSION-beta"
template: |
  ## Changes
  {{#each .Versions}}
  ### {{#if .Name}}{{.Name.split('.')[0]}}{{else}}Unreleased{{/if}}
  {{#each .PullRequests}}
  - {{#if .Draft}}{{.Number}}: (DRAFT){{else}}{{.Number}}:{{/if}} {{title}} ({{user.login}})
  {{/each}}
  {{/each}}
