template: |

  ## This is a beta release

categories:
  - type: "pre-exclude"
    when:
      labels:
        - skip-changelog

  - title: 🚀 Features
    when:
      labels:
        - feature
        - enhancement
  - title: 🐛 Bug Fixes
    when:
      labels:
        - fix
        - bug
  - title: ⚠️ Breaking
    when:
      labels:
        - breaking
  - title: ⚠️ Changes
    when:
      labels:
        - changed
  - title: ⛔️ Deprecated
    when:
      labels:
        - deprecated
  - title: 🗑 Removed
    when:
      labels:
        - removed
  - title: 🔐 Security
    when:
      labels:
        - security
  - title: 📄 Documentation
    when:
      labels:
        - docs
        - documentation
  - title: 🧩 Dependency Updates
    when:
      labels:
        - deps
        - dependencies

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
