start:
  name: Start the mower
  description: "Start the Robonect mower."

stop:
  name: Stop the mower
  description: "Stop the Robonect mower."

reboot:
  name: Reboot the mower
  description: "Reboots the Robonect mower."

shutdown:
  name: Shuts the mower down
  description: "Shuts the Robonect mower down."

sleep:
  name: Set the mower to sleep
  description: "Sets the Robonect mower to sleep."

operation_mode:
  name: Set the operation mode
  description: Set the operation mode of the mower.
  fields:
    mode:
      name: Operation mode
      description: Operation mode of the mower
      example: "eod"
      default: "auto"
      selector:
        select:
          options:
            - "man"
            - "auto"
            - "eod"
            - "home"

job:
  name: Place a mowing job
  description: Mower performs a mowing job
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the Robonect Vacuum
      required: true
      example: vacuum.automower_robonect
      selector:
        entity:
          domain: vacuum
          integration: robonect
    start:
      name: Start time
      description: Start time 'hh:mm', if omitted, then 'Immediately' applies.
      example: "10:00"
      selector:
        time:
    end:
      name: End time
      description: End time 'hh:mm'.
      example: "13:00"
      selector:
        time:
    duration:
      name: Duration
      description: Duration of the job in minutes. If the mower is charging, the 'clock' continues. Omitted if end is set.
      example: "145"
      selector:
        number:
          min: 1
          max: 10080
          mode: box
          unit_of_measurement: min
    after:
      name: After mode
      description: Mode that will be activated after this mowing job is done.
      example: "Auto"
      default: "Auto"
      selector:
        select:
          options:
            - "Auto"
            - "Home"
            - "End of day"
    corridor:
      name: Corridor width
      description: Corridor width. If omitted, it will be set to Normal
      example: "Normal"
      default: "Normal"
      selector:
        select:
          options:
            - "Normal"
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
    remotestart:
      name: Remote start
      description: The remote mowing starting point.
      default: "Normal"
      selector:
        select:
          options:
            - "Normal"
            - "From charging station"
            - "Remote start 1"
            - "Remote start 2"
            - "Remote start 3"
            - "Remote start 4"
            - "Remote start 5"
timer:
  name: Modify a timer
  description: Modify a Robonect timer
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the Robonect Vacuum
      required: true
      example: vacuum.automower_robonect
      selector:
        entity:
          domain: vacuum
          integration: robonect
    timer:
      name: Timer
      description: Timer ID
      required: true
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
    enable:
      name: Enable
      required: true
      description: Timer enable
      selector:
        boolean:
    start:
      name: Start time
      required: true
      description: Start time 'hh:mm'
      example: "10:00"
      selector:
        time:
    end:
      name: End time
      required: true
      description: End time 'hh:mm'
      example: "13:00"
      selector:
        time:
    weekdays:
      name: Weekdays
      required: true
      description: Weekdays
      selector:
        select:
          multiple: true
          mode: list
          translation_key: weekdays
          options:
            - label: Monday
              value: mo
            - label: Tuesday
              value: tu
            - label: Wednesday
              value: we
            - label: Thursday
              value: th
            - label: Friday
              value: fr
            - label: Saturday
              value: sa
            - label: Sunday
              value: su

direct:
  name: Direct the mower
  description: Direct a Robonect mower by setting the speed percentage for each wheel and a duration
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the Robonect Vacuum
      required: true
      example: vacuum.automower_robonect
      selector:
        entity:
          domain: vacuum
          integration: robonect
    left:
      name: Left
      description: "The percentage of speed on the left wheel. Can be positive or negative."
      required: true
      example: 50
      selector:
        number:
          mode: box
          unit_of_measurement: "%"
    right:
      name: Right
      description: "The percentage of speed on the right wheel. Can be positive or negative."
      required: true
      example: 50
      selector:
        number:
          mode: box
          unit_of_measurement: "%"
    timeout:
      name: Timeout
      description: "The timeout/duration in milliseconds."
      required: true
      example: 3000
      selector:
        number:
          min: 1
          max: 5000
          mode: box
          unit_of_measurement: ms
