blueprint:
  name: Daily Sync Robonect Time To DST
  description: >
    Presses the Robonect time sync button at a specific time each day.
    The Robonect device will synchronize its clock using SNTP and update daylight saving settings.
  domain: automation
  input:
    sync_time:
      name: Sync Time
      description: Time of day when the sync should run.
      default: "04:00:00" # default placeholder for YAML validation
      selector:
        time: {}
    winter_mode:
      name: Winter mode
      description: The winter mode binary sensor
      default: binary_sensor.automower_winter_mode
      selector:
        entity:
          domain: binary_sensor
    target_button:
      name: Target Button
      description: The Robonect button entity to press for time synchronization.
      default: button.automower_sync_clock # default placeholder for YAML validation
      selector:
        entity:
          domain: button

trigger:
  - platform: time
    at: !input sync_time # Home Assistant will resolve !input at runtime

conditions:
  - condition: state
    entity_id: !input winter_mode # Home Assistant will resolve !input at runtime
    state:
      - "off"

action:
  - service: button.press
    target:
      entity_id: !input target_button # Home Assistant will resolve !input at runtime

mode: single
